name: deploy-eqtlcoloc

on:
  push:
    branches:
      - main
    paths:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd app && docker build -t cubrenig/pgwaseqtlcoloc:latest -t cubrenig/pgwaseqtlcoloc:$GITHUB_SHA .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push cubrenig/pgwaseqtlcoloc:latest
      - run: docker push cubrenig/pgwaseqtlcoloc:$GITHUB_SHA
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'placeholder to avoid errors'
#          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Copy files with rsync
        run: rsync -avz ${{ github.workspace }}/ ${{ secrets.USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.HOME_DIR }}/files/dist/eqtlcoloc/
      - name: run script commands via ssh
        uses: appleboy/ssh-action@master
        env:
          SHA: ${{ github.sha }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          envs: SHA
          script: |
            echo $SHA > ${{ secrets.HOME_DIR }}/myfile.txt
            helm upgrade eqtl-coloc ${{ secrets.HOME_DIR }}/files/dist/eqtlcoloc/infra/helm/ --install --wait --set image=cubrenig/pgwaseqtlcoloc:$SHA --values=${{ secrets.HOME_DIR }}/files/dist/eqtlcoloc/infra/helm/micro-values.yaml